### ISSUE TITLE
No environment.yaml and requirements.txt

### ISSUE THREAD

**Issue by yuxiaoliu2020** [l1997i/lim3d#2]
Hello l1997i,

Thank you for sharing your work ! I am very interested in replicating the results and exploring the code further. However, I noticed that the repository does not include an `environment.yaml` or `requirements.txt` file specifying the dependencies and their versions.

Could you kindly provide either an `environment.yaml` or `requirements.txt` file? This would greatly help in setting up the correct environment to ensure that everything runs smoothly.

Thank you for your time and assistance.

Best regards

**Comment by l1997i** [comment]
Hello @Heathogata,

Thank you very much for your feedback. I have updated the repo and attached the `requirements.txt` file in https://github.com/l1997i/lim3d/commit/2f250b17a9585e3b5f24602f44c2e0d364bc0a17. Hope it helps!

Cheers.
